# Generated by Django 5.0.1 on 2026-02-10 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(help_text='Original ID from OPIS dataset', max_length=50, verbose_name='OPIS Truckstop ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Station Name')),
                ('address', models.TextField(help_text='Full address including highway references', verbose_name='Address')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(db_index=True, help_text='Two-letter US state code (e.g., CA, NY)', max_length=2, verbose_name='State Code')),
                ('rack_id', models.IntegerField(blank=True, null=True, verbose_name='Rack ID')),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=3, help_text='Price per gallon in USD', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.999)], verbose_name='Retail Price (per gallon)')),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Latitude in decimal degrees', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text='Longitude in decimal degrees', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('geocoded', models.BooleanField(db_index=True, default=False, help_text='Whether this station has been geocoded', verbose_name='Geocoded')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['retail_price', 'name'],
                'indexes': [models.Index(fields=['geocoded', 'retail_price'], name='optimizer_f_geocode_66c5cc_idx'), models.Index(fields=['state', 'city'], name='optimizer_f_state_c4ef99_idx'), models.Index(fields=['latitude', 'longitude'], name='optimizer_f_latitud_5b4a28_idx')],
            },
        ),
    ]
